name: Prague
favicon: null
layout_spectrum: 0.2979261609725654
typography_spectrum: 0.8629346555098891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4083898572716862
  lightness: 0.6821926978882402
  saturation: 0.770668635610491
  rhythmicContrast: 0.4677031822502613
purpose: []
