name: Prague
favicon: null
layout_spectrum: 0.9002
typography_spectrum: 0.47819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f2f2f'
    - '#787878'
    - '#dcdcdc'
    - '#ffffff'
    - '#bcbcbc'
  brandStrength: 0.25
  lightness: 0.6821926978882402
  saturation: 0.770668635610491
  rhythmicContrast: 0.75
purpose: []
